query GetShoe($id: ID, $locale: I18NLocaleCode) {
  shoe(id: $id, locale: $locale) {
    data {
      attributes {
        name
        description
        content
        details
        price
        options {
          id
          medias {
            data {
              id
              attributes {
                url
                name
                previewUrl
              }
            }
          }
          color
        }
        type
      }
    }
  }
}
