query GetSectionDiscount($locale: I18NLocaleCode) {
  sectionDiscount(locale: $locale) {
    data {
      attributes {
        items {
          ...DiscountAttributesFragment
        }
      }
    }
  }
}
