import { notFound } from "next/navigation";

import type { Metadata } from "next";

import { Languages, languages } from "@/shared/i18n/types";

import { PreHeader } from "./_layouts/PreHeader";
import { Header } from "./_layouts/Header";

import { gql } from "@/graphql/client";

import "@/shared/assets/styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: Languages };
}) {
  if (!languages.includes(params.locale as Languages)) notFound();

  const { preHeader } = await gql.GetPreHeader({
    locale: params.locale,
  });

  const { linkLists } = await gql.GetHeaderLinkList({
    locale: params.locale,
  });

  const { i18NLocales } = await gql.GetLocale();

  const localeCodes = i18NLocales.data.map(
    (el) => el.attributes.code
  ) as Languages[];

  return (
    <html lang={params.locale}>
      <body>
        {preHeader && (
          <PreHeader preHeader={preHeader.data} localeCodes={localeCodes} />
        )}
        {linkLists && <Header linkLists={linkLists.data} />}

        <main>{children}</main>
      </body>
    </html>
  );
}
